# Generated by Django 6.0.5 on 2026-05-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollutionreport',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pollutionreport',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pollutionreport',
            name='user',
        ),
        migrations.AlterField(
            model_name='pollutionreport',
            name='latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pollutionreport',
            name='longitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pollutionreport',
            name='pollution_type',
            field=models.CharField(max_length=100),
        ),
    ]
