# Generated by Django 6.0.5 on 2026-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_pollutionreport_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutionreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pollution_images/'),
        ),
    ]
