# Generated by Django 6.0.5 on 2026-05-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_pollutionreport_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutionreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pollution_reports/'),
        ),
        migrations.AlterField(
            model_name='pollutionreport',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pollutionreport',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
