# Generated by Django 6.0.5 on 2026-05-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_pollutionreport_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutionreport',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pollutionreport',
            name='latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pollutionreport',
            name='longitude',
            field=models.CharField(max_length=100),
        ),
    ]
