# Generated by Django 6.0.5 on 2026-05-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buoy_id', models.CharField(max_length=100)),
                ('ph', models.FloatField()),
                ('turbidity', models.FloatField()),
                ('salinity', models.FloatField()),
                ('oil_detected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
