# Generated by Django 6.0.5 on 2026-06-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='buoy_id',
            field=models.CharField(default='BUOY_001', max_length=100),
        ),
    ]
