# Generated by Django 6.0.5 on 2026-05-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('organization', 'Organization'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
